// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C_Chat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_12_23(); }
  public static C_Chat GetRootAsC_Chat(ByteBuffer _bb) { return GetRootAsC_Chat(_bb, new C_Chat()); }
  public static C_Chat GetRootAsC_Chat(ByteBuffer _bb, C_Chat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C_Chat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Text { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTextBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetTextBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetTextArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<C_Chat> CreateC_Chat(FlatBufferBuilder builder,
      StringOffset textOffset = default(StringOffset)) {
    builder.StartTable(1);
    C_Chat.AddText(builder, textOffset);
    return C_Chat.EndC_Chat(builder);
  }

  public static void StartC_Chat(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddText(FlatBufferBuilder builder, StringOffset textOffset) { builder.AddOffset(0, textOffset.Value, 0); }
  public static Offset<C_Chat> EndC_Chat(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<C_Chat>(o);
  }
}


static public class C_ChatVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Text*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
