// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C_MOVE : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_12_23(); }
  public static C_MOVE GetRootAsC_MOVE(ByteBuffer _bb) { return GetRootAsC_MOVE(_bb, new C_MOVE()); }
  public static C_MOVE GetRootAsC_MOVE(ByteBuffer _bb, C_MOVE obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C_MOVE __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PositionInfo? PosInfo { get { int o = __p.__offset(4); return o != 0 ? (PositionInfo?)(new PositionInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<C_MOVE> CreateC_MOVE(FlatBufferBuilder builder,
      Offset<PositionInfo> posInfoOffset = default(Offset<PositionInfo>)) {
    builder.StartTable(1);
    C_MOVE.AddPosInfo(builder, posInfoOffset);
    return C_MOVE.EndC_MOVE(builder);
  }

  public static void StartC_MOVE(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPosInfo(FlatBufferBuilder builder, Offset<PositionInfo> posInfoOffset) { builder.AddOffset(0, posInfoOffset.Value, 0); }
  public static Offset<C_MOVE> EndC_MOVE(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<C_MOVE>(o);
  }
}


static public class C_MOVEVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*PosInfo*/, PositionInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
