// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C_Test : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_12_23(); }
  public static C_Test GetRootAsC_Test(ByteBuffer _bb) { return GetRootAsC_Test(_bb, new C_Test()); }
  public static C_Test GetRootAsC_Test(ByteBuffer _bb, C_Test obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C_Test __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int TestC { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<C_Test> CreateC_Test(FlatBufferBuilder builder,
      int test_c = 0) {
    builder.StartTable(1);
    C_Test.AddTestC(builder, test_c);
    return C_Test.EndC_Test(builder);
  }

  public static void StartC_Test(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTestC(FlatBufferBuilder builder, int testC) { builder.AddInt(0, testC, 0); }
  public static Offset<C_Test> EndC_Test(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<C_Test>(o);
  }
}


static public class C_TestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*TestC*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
