// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct D_Test : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_12_23(); }
  public static D_Test GetRootAsD_Test(ByteBuffer _bb) { return GetRootAsD_Test(_bb, new D_Test()); }
  public static D_Test GetRootAsD_Test(ByteBuffer _bb, D_Test obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public D_Test __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int TestD { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<D_Test> CreateD_Test(FlatBufferBuilder builder,
      int test_d = 0) {
    builder.StartTable(1);
    D_Test.AddTestD(builder, test_d);
    return D_Test.EndD_Test(builder);
  }

  public static void StartD_Test(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTestD(FlatBufferBuilder builder, int testD) { builder.AddInt(0, testD, 0); }
  public static Offset<D_Test> EndD_Test(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<D_Test>(o);
  }
}


static public class D_TestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*TestD*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
