// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_ENTER_GAME : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_12_23(); }
  public static SC_ENTER_GAME GetRootAsSC_ENTER_GAME(ByteBuffer _bb) { return GetRootAsSC_ENTER_GAME(_bb, new SC_ENTER_GAME()); }
  public static SC_ENTER_GAME GetRootAsSC_ENTER_GAME(ByteBuffer _bb, SC_ENTER_GAME obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_ENTER_GAME __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PlayerInfo? Player { get { int o = __p.__offset(4); return o != 0 ? (PlayerInfo?)(new PlayerInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<SC_ENTER_GAME> CreateSC_ENTER_GAME(FlatBufferBuilder builder,
      Offset<PlayerInfo> playerOffset = default(Offset<PlayerInfo>)) {
    builder.StartTable(1);
    SC_ENTER_GAME.AddPlayer(builder, playerOffset);
    return SC_ENTER_GAME.EndSC_ENTER_GAME(builder);
  }

  public static void StartSC_ENTER_GAME(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayer(FlatBufferBuilder builder, Offset<PlayerInfo> playerOffset) { builder.AddOffset(0, playerOffset.Value, 0); }
  public static Offset<SC_ENTER_GAME> EndSC_ENTER_GAME(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_ENTER_GAME>(o);
  }
}


static public class SC_ENTER_GAMEVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Player*/, PlayerInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
