// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "Test_generated.h"

enum PacketType : uint8_t {
  PacketType_NONE = 0,
  PacketType_C_Test = 1,
  PacketType_SD_Test = 2,
  PacketType_D_Test = 3,
  PacketType_SC_Test = 4,
  PacketType_MIN = PacketType_NONE,
  PacketType_MAX = PacketType_SC_Test
};

inline const PacketType (&EnumValuesPacketType())[5] {
  static const PacketType values[] = {
    PacketType_NONE,
    PacketType_C_Test,
    PacketType_SD_Test,
    PacketType_D_Test,
    PacketType_SC_Test
  };
  return values;
}

inline const char * const *EnumNamesPacketType() {
  static const char * const names[6] = {
    "NONE",
    "C_Test",
    "SD_Test",
    "D_Test",
    "SC_Test",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketType(PacketType e) {
  if (::flatbuffers::IsOutRange(e, PacketType_NONE, PacketType_SC_Test)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketType()[index];
}

template<typename T> struct PacketTypeTraits {
  static const PacketType enum_value = PacketType_NONE;
};

template<> struct PacketTypeTraits<C_Test> {
  static const PacketType enum_value = PacketType_C_Test;
};

template<> struct PacketTypeTraits<SD_Test> {
  static const PacketType enum_value = PacketType_SD_Test;
};

template<> struct PacketTypeTraits<D_Test> {
  static const PacketType enum_value = PacketType_D_Test;
};

template<> struct PacketTypeTraits<SC_Test> {
  static const PacketType enum_value = PacketType_SC_Test;
};

bool VerifyPacketType(::flatbuffers::Verifier &verifier, const void *obj, PacketType type);
bool VerifyPacketTypeVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

inline bool VerifyPacketType(::flatbuffers::Verifier &verifier, const void *obj, PacketType type) {
  switch (type) {
    case PacketType_NONE: {
      return true;
    }
    case PacketType_C_Test: {
      auto ptr = reinterpret_cast<const C_Test *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_Test: {
      auto ptr = reinterpret_cast<const SD_Test *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_Test: {
      auto ptr = reinterpret_cast<const D_Test *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_Test: {
      auto ptr = reinterpret_cast<const SC_Test *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPacketTypeVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPacketType(
        verifier,  values->Get(i), types->GetEnum<PacketType>(i))) {
      return false;
    }
  }
  return true;
}

#endif  // FLATBUFFERS_GENERATED_PROTOCOL_H_
