// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "Chat_generated.h"
#include "Heartbeat_generated.h"
#include "InGame_generated.h"
#include "Login_generated.h"

enum PacketType : uint8_t {
  PacketType_NONE = 0,
  PacketType_C_ENTER_GAME = 1,
  PacketType_SC_ENTER_GAME = 2,
  PacketType_SC_LEAVE_GAME = 3,
  PacketType_SC_SPAWN = 4,
  PacketType_SC_DESPAWN = 5,
  PacketType_C_MOVE = 6,
  PacketType_SC_MOVE = 7,
  PacketType_C_CHAT = 8,
  PacketType_SC_CHAT = 9,
  PacketType_C_SKILL = 10,
  PacketType_SC_SKILL = 11,
  PacketType_SC_CHANGE_HP = 12,
  PacketType_SC_DIE = 13,
  PacketType_SC_ITEM_LIST = 14,
  PacketType_C_EQUIP_ITEM = 15,
  PacketType_SC_EQUIP_ITEM = 16,
  PacketType_C_CHANGE_MAP = 17,
  PacketType_SC_CHANGE_MAP = 18,
  PacketType_C_SIGNUP = 19,
  PacketType_SD_SIGNUP = 20,
  PacketType_D_SIGNUP = 21,
  PacketType_SC_SIGNUP = 22,
  PacketType_C_SIGNIN = 23,
  PacketType_SD_SIGNIN = 24,
  PacketType_D_SIGNIN = 25,
  PacketType_SC_SIGNIN = 26,
  PacketType_C_HEARTBEAT = 27,
  PacketType_SC_HEARTBEAT = 28,
  PacketType_MIN = PacketType_NONE,
  PacketType_MAX = PacketType_SC_HEARTBEAT
};

inline const PacketType (&EnumValuesPacketType())[29] {
  static const PacketType values[] = {
    PacketType_NONE,
    PacketType_C_ENTER_GAME,
    PacketType_SC_ENTER_GAME,
    PacketType_SC_LEAVE_GAME,
    PacketType_SC_SPAWN,
    PacketType_SC_DESPAWN,
    PacketType_C_MOVE,
    PacketType_SC_MOVE,
    PacketType_C_CHAT,
    PacketType_SC_CHAT,
    PacketType_C_SKILL,
    PacketType_SC_SKILL,
    PacketType_SC_CHANGE_HP,
    PacketType_SC_DIE,
    PacketType_SC_ITEM_LIST,
    PacketType_C_EQUIP_ITEM,
    PacketType_SC_EQUIP_ITEM,
    PacketType_C_CHANGE_MAP,
    PacketType_SC_CHANGE_MAP,
    PacketType_C_SIGNUP,
    PacketType_SD_SIGNUP,
    PacketType_D_SIGNUP,
    PacketType_SC_SIGNUP,
    PacketType_C_SIGNIN,
    PacketType_SD_SIGNIN,
    PacketType_D_SIGNIN,
    PacketType_SC_SIGNIN,
    PacketType_C_HEARTBEAT,
    PacketType_SC_HEARTBEAT
  };
  return values;
}

inline const char * const *EnumNamesPacketType() {
  static const char * const names[30] = {
    "NONE",
    "C_ENTER_GAME",
    "SC_ENTER_GAME",
    "SC_LEAVE_GAME",
    "SC_SPAWN",
    "SC_DESPAWN",
    "C_MOVE",
    "SC_MOVE",
    "C_CHAT",
    "SC_CHAT",
    "C_SKILL",
    "SC_SKILL",
    "SC_CHANGE_HP",
    "SC_DIE",
    "SC_ITEM_LIST",
    "C_EQUIP_ITEM",
    "SC_EQUIP_ITEM",
    "C_CHANGE_MAP",
    "SC_CHANGE_MAP",
    "C_SIGNUP",
    "SD_SIGNUP",
    "D_SIGNUP",
    "SC_SIGNUP",
    "C_SIGNIN",
    "SD_SIGNIN",
    "D_SIGNIN",
    "SC_SIGNIN",
    "C_HEARTBEAT",
    "SC_HEARTBEAT",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketType(PacketType e) {
  if (::flatbuffers::IsOutRange(e, PacketType_NONE, PacketType_SC_HEARTBEAT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketType()[index];
}

template<typename T> struct PacketTypeTraits {
  static const PacketType enum_value = PacketType_NONE;
};

template<> struct PacketTypeTraits<C_ENTER_GAME> {
  static const PacketType enum_value = PacketType_C_ENTER_GAME;
};

template<> struct PacketTypeTraits<SC_ENTER_GAME> {
  static const PacketType enum_value = PacketType_SC_ENTER_GAME;
};

template<> struct PacketTypeTraits<SC_LEAVE_GAME> {
  static const PacketType enum_value = PacketType_SC_LEAVE_GAME;
};

template<> struct PacketTypeTraits<SC_SPAWN> {
  static const PacketType enum_value = PacketType_SC_SPAWN;
};

template<> struct PacketTypeTraits<SC_DESPAWN> {
  static const PacketType enum_value = PacketType_SC_DESPAWN;
};

template<> struct PacketTypeTraits<C_MOVE> {
  static const PacketType enum_value = PacketType_C_MOVE;
};

template<> struct PacketTypeTraits<SC_MOVE> {
  static const PacketType enum_value = PacketType_SC_MOVE;
};

template<> struct PacketTypeTraits<C_CHAT> {
  static const PacketType enum_value = PacketType_C_CHAT;
};

template<> struct PacketTypeTraits<SC_CHAT> {
  static const PacketType enum_value = PacketType_SC_CHAT;
};

template<> struct PacketTypeTraits<C_SKILL> {
  static const PacketType enum_value = PacketType_C_SKILL;
};

template<> struct PacketTypeTraits<SC_SKILL> {
  static const PacketType enum_value = PacketType_SC_SKILL;
};

template<> struct PacketTypeTraits<SC_CHANGE_HP> {
  static const PacketType enum_value = PacketType_SC_CHANGE_HP;
};

template<> struct PacketTypeTraits<SC_DIE> {
  static const PacketType enum_value = PacketType_SC_DIE;
};

template<> struct PacketTypeTraits<SC_ITEM_LIST> {
  static const PacketType enum_value = PacketType_SC_ITEM_LIST;
};

template<> struct PacketTypeTraits<C_EQUIP_ITEM> {
  static const PacketType enum_value = PacketType_C_EQUIP_ITEM;
};

template<> struct PacketTypeTraits<SC_EQUIP_ITEM> {
  static const PacketType enum_value = PacketType_SC_EQUIP_ITEM;
};

template<> struct PacketTypeTraits<C_CHANGE_MAP> {
  static const PacketType enum_value = PacketType_C_CHANGE_MAP;
};

template<> struct PacketTypeTraits<SC_CHANGE_MAP> {
  static const PacketType enum_value = PacketType_SC_CHANGE_MAP;
};

template<> struct PacketTypeTraits<C_SIGNUP> {
  static const PacketType enum_value = PacketType_C_SIGNUP;
};

template<> struct PacketTypeTraits<SD_SIGNUP> {
  static const PacketType enum_value = PacketType_SD_SIGNUP;
};

template<> struct PacketTypeTraits<D_SIGNUP> {
  static const PacketType enum_value = PacketType_D_SIGNUP;
};

template<> struct PacketTypeTraits<SC_SIGNUP> {
  static const PacketType enum_value = PacketType_SC_SIGNUP;
};

template<> struct PacketTypeTraits<C_SIGNIN> {
  static const PacketType enum_value = PacketType_C_SIGNIN;
};

template<> struct PacketTypeTraits<SD_SIGNIN> {
  static const PacketType enum_value = PacketType_SD_SIGNIN;
};

template<> struct PacketTypeTraits<D_SIGNIN> {
  static const PacketType enum_value = PacketType_D_SIGNIN;
};

template<> struct PacketTypeTraits<SC_SIGNIN> {
  static const PacketType enum_value = PacketType_SC_SIGNIN;
};

template<> struct PacketTypeTraits<C_HEARTBEAT> {
  static const PacketType enum_value = PacketType_C_HEARTBEAT;
};

template<> struct PacketTypeTraits<SC_HEARTBEAT> {
  static const PacketType enum_value = PacketType_SC_HEARTBEAT;
};

bool VerifyPacketType(::flatbuffers::Verifier &verifier, const void *obj, PacketType type);
bool VerifyPacketTypeVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

inline bool VerifyPacketType(::flatbuffers::Verifier &verifier, const void *obj, PacketType type) {
  switch (type) {
    case PacketType_NONE: {
      return true;
    }
    case PacketType_C_ENTER_GAME: {
      auto ptr = reinterpret_cast<const C_ENTER_GAME *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_ENTER_GAME: {
      auto ptr = reinterpret_cast<const SC_ENTER_GAME *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_LEAVE_GAME: {
      auto ptr = reinterpret_cast<const SC_LEAVE_GAME *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_SPAWN: {
      auto ptr = reinterpret_cast<const SC_SPAWN *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_DESPAWN: {
      auto ptr = reinterpret_cast<const SC_DESPAWN *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_MOVE: {
      auto ptr = reinterpret_cast<const C_MOVE *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_MOVE: {
      auto ptr = reinterpret_cast<const SC_MOVE *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_CHAT: {
      auto ptr = reinterpret_cast<const C_CHAT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CHAT: {
      auto ptr = reinterpret_cast<const SC_CHAT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_SKILL: {
      auto ptr = reinterpret_cast<const C_SKILL *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_SKILL: {
      auto ptr = reinterpret_cast<const SC_SKILL *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CHANGE_HP: {
      auto ptr = reinterpret_cast<const SC_CHANGE_HP *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_DIE: {
      auto ptr = reinterpret_cast<const SC_DIE *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_ITEM_LIST: {
      auto ptr = reinterpret_cast<const SC_ITEM_LIST *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_EQUIP_ITEM: {
      auto ptr = reinterpret_cast<const C_EQUIP_ITEM *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_EQUIP_ITEM: {
      auto ptr = reinterpret_cast<const SC_EQUIP_ITEM *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_CHANGE_MAP: {
      auto ptr = reinterpret_cast<const C_CHANGE_MAP *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CHANGE_MAP: {
      auto ptr = reinterpret_cast<const SC_CHANGE_MAP *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_SIGNUP: {
      auto ptr = reinterpret_cast<const C_SIGNUP *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_SIGNUP: {
      auto ptr = reinterpret_cast<const SD_SIGNUP *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_SIGNUP: {
      auto ptr = reinterpret_cast<const D_SIGNUP *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_SIGNUP: {
      auto ptr = reinterpret_cast<const SC_SIGNUP *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_SIGNIN: {
      auto ptr = reinterpret_cast<const C_SIGNIN *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_SIGNIN: {
      auto ptr = reinterpret_cast<const SD_SIGNIN *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_SIGNIN: {
      auto ptr = reinterpret_cast<const D_SIGNIN *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_SIGNIN: {
      auto ptr = reinterpret_cast<const SC_SIGNIN *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_HEARTBEAT: {
      auto ptr = reinterpret_cast<const C_HEARTBEAT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_HEARTBEAT: {
      auto ptr = reinterpret_cast<const SC_HEARTBEAT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPacketTypeVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPacketType(
        verifier,  values->Get(i), types->GetEnum<PacketType>(i))) {
      return false;
    }
  }
  return true;
}

#endif  // FLATBUFFERS_GENERATED_PROTOCOL_H_
