// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CHAT_H_
#define FLATBUFFERS_GENERATED_CHAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "InGame_generated.h"

struct C_Chat;
struct C_ChatBuilder;

struct SC_Chat;
struct SC_ChatBuilder;

struct C_Chat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C_ChatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEXT = 4
  };
  const ::flatbuffers::String *text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TEXT) &&
           verifier.VerifyString(text()) &&
           verifier.EndTable();
  }
};

struct C_ChatBuilder {
  typedef C_Chat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_text(::flatbuffers::Offset<::flatbuffers::String> text) {
    fbb_.AddOffset(C_Chat::VT_TEXT, text);
  }
  explicit C_ChatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C_Chat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C_Chat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C_Chat> CreateC_Chat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> text = 0) {
  C_ChatBuilder builder_(_fbb);
  builder_.add_text(text);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<C_Chat> CreateC_ChatDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *text = nullptr) {
  auto text__ = text ? _fbb.CreateString(text) : 0;
  return CreateC_Chat(
      _fbb,
      text__);
}

struct SC_Chat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_ChatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER = 4,
    VT_TEXT = 6
  };
  const PlayerInfo *player() const {
    return GetPointer<const PlayerInfo *>(VT_PLAYER);
  }
  const ::flatbuffers::String *text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PLAYER) &&
           verifier.VerifyTable(player()) &&
           VerifyOffset(verifier, VT_TEXT) &&
           verifier.VerifyString(text()) &&
           verifier.EndTable();
  }
};

struct SC_ChatBuilder {
  typedef SC_Chat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player(::flatbuffers::Offset<PlayerInfo> player) {
    fbb_.AddOffset(SC_Chat::VT_PLAYER, player);
  }
  void add_text(::flatbuffers::Offset<::flatbuffers::String> text) {
    fbb_.AddOffset(SC_Chat::VT_TEXT, text);
  }
  explicit SC_ChatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_Chat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_Chat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_Chat> CreateSC_Chat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<PlayerInfo> player = 0,
    ::flatbuffers::Offset<::flatbuffers::String> text = 0) {
  SC_ChatBuilder builder_(_fbb);
  builder_.add_text(text);
  builder_.add_player(player);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SC_Chat> CreateSC_ChatDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<PlayerInfo> player = 0,
    const char *text = nullptr) {
  auto text__ = text ? _fbb.CreateString(text) : 0;
  return CreateSC_Chat(
      _fbb,
      player,
      text__);
}

#endif  // FLATBUFFERS_GENERATED_CHAT_H_
