// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum ObjectState : sbyte
{
  IDLE = 0,
  MOVING = 1,
  SKILL = 2,
  DEAD = 3,
};

