// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum PacketType : byte
{
  NONE = 0,
  SC_ENTER_GAME = 1,
  SC_LEAVE_GAME = 2,
  SC_SPAWN = 3,
  SC_DESPAWN = 4,
  C_MOVE = 5,
  SC_MOVE = 6,
  C_CHAT = 7,
  SC_CHAT = 8,
  C_SKILL = 9,
  SC_SKILL = 10,
};



static public class PacketTypeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((PacketType)typeId)
    {
      case PacketType.SC_ENTER_GAME:
        result = SC_ENTER_GAMEVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_LEAVE_GAME:
        result = SC_LEAVE_GAMEVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_SPAWN:
        result = SC_SPAWNVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_DESPAWN:
        result = SC_DESPAWNVerify.Verify(verifier, tablePos);
        break;
      case PacketType.C_MOVE:
        result = C_MOVEVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_MOVE:
        result = SC_MOVEVerify.Verify(verifier, tablePos);
        break;
      case PacketType.C_CHAT:
        result = C_CHATVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_CHAT:
        result = SC_CHATVerify.Verify(verifier, tablePos);
        break;
      case PacketType.C_SKILL:
        result = C_SKILLVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_SKILL:
        result = SC_SKILLVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

