// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PositionInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_12_23(); }
  public static PositionInfo GetRootAsPositionInfo(ByteBuffer _bb) { return GetRootAsPositionInfo(_bb, new PositionInfo()); }
  public static PositionInfo GetRootAsPositionInfo(ByteBuffer _bb, PositionInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PositionInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ObjectState State { get { int o = __p.__offset(4); return o != 0 ? (ObjectState)__p.bb.GetSbyte(o + __p.bb_pos) : ObjectState.IDLE; } }
  public MoveDir MoveDir { get { int o = __p.__offset(6); return o != 0 ? (MoveDir)__p.bb.GetSbyte(o + __p.bb_pos) : MoveDir.NONE; } }
  public int PosX { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int PosY { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PositionInfo> CreatePositionInfo(FlatBufferBuilder builder,
      ObjectState state = ObjectState.IDLE,
      MoveDir moveDir = MoveDir.NONE,
      int posX = 0,
      int posY = 0) {
    builder.StartTable(4);
    PositionInfo.AddPosY(builder, posY);
    PositionInfo.AddPosX(builder, posX);
    PositionInfo.AddMoveDir(builder, moveDir);
    PositionInfo.AddState(builder, state);
    return PositionInfo.EndPositionInfo(builder);
  }

  public static void StartPositionInfo(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddState(FlatBufferBuilder builder, ObjectState state) { builder.AddSbyte(0, (sbyte)state, 0); }
  public static void AddMoveDir(FlatBufferBuilder builder, MoveDir moveDir) { builder.AddSbyte(1, (sbyte)moveDir, 0); }
  public static void AddPosX(FlatBufferBuilder builder, int posX) { builder.AddInt(2, posX, 0); }
  public static void AddPosY(FlatBufferBuilder builder, int posY) { builder.AddInt(3, posY, 0); }
  public static Offset<PositionInfo> EndPositionInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PositionInfo>(o);
  }
}


static public class PositionInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*State*/, 1 /*ObjectState*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*MoveDir*/, 1 /*MoveDir*/, 1, false)
      && verifier.VerifyField(tablePos, 8 /*PosX*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*PosY*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
