// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_LEAVE_GAME : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_12_23(); }
  public static SC_LEAVE_GAME GetRootAsSC_LEAVE_GAME(ByteBuffer _bb) { return GetRootAsSC_LEAVE_GAME(_bb, new SC_LEAVE_GAME()); }
  public static SC_LEAVE_GAME GetRootAsSC_LEAVE_GAME(ByteBuffer _bb, SC_LEAVE_GAME obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_LEAVE_GAME __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSC_LEAVE_GAME(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<SC_LEAVE_GAME> EndSC_LEAVE_GAME(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_LEAVE_GAME>(o);
  }
}


static public class SC_LEAVE_GAMEVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}
