// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_SKILL : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_12_23(); }
  public static SC_SKILL GetRootAsSC_SKILL(ByteBuffer _bb) { return GetRootAsSC_SKILL(_bb, new SC_SKILL()); }
  public static SC_SKILL GetRootAsSC_SKILL(ByteBuffer _bb, SC_SKILL obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_SKILL __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public SkillInfo? SkillInfo { get { int o = __p.__offset(6); return o != 0 ? (SkillInfo?)(new SkillInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<SC_SKILL> CreateSC_SKILL(FlatBufferBuilder builder,
      int playerId = 0,
      Offset<SkillInfo> skillInfoOffset = default(Offset<SkillInfo>)) {
    builder.StartTable(2);
    SC_SKILL.AddSkillInfo(builder, skillInfoOffset);
    SC_SKILL.AddPlayerId(builder, playerId);
    return SC_SKILL.EndSC_SKILL(builder);
  }

  public static void StartSC_SKILL(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPlayerId(FlatBufferBuilder builder, int playerId) { builder.AddInt(0, playerId, 0); }
  public static void AddSkillInfo(FlatBufferBuilder builder, Offset<SkillInfo> skillInfoOffset) { builder.AddOffset(1, skillInfoOffset.Value, 0); }
  public static Offset<SC_SKILL> EndSC_SKILL(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_SKILL>(o);
  }
}


static public class SC_SKILLVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayerId*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*SkillInfo*/, SkillInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
