// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SkillInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_12_23(); }
  public static SkillInfo GetRootAsSkillInfo(ByteBuffer _bb) { return GetRootAsSkillInfo(_bb, new SkillInfo()); }
  public static SkillInfo GetRootAsSkillInfo(ByteBuffer _bb, SkillInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SkillInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int SkillId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<SkillInfo> CreateSkillInfo(FlatBufferBuilder builder,
      int skillId = 0) {
    builder.StartTable(1);
    SkillInfo.AddSkillId(builder, skillId);
    return SkillInfo.EndSkillInfo(builder);
  }

  public static void StartSkillInfo(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddSkillId(FlatBufferBuilder builder, int skillId) { builder.AddInt(0, skillId, 0); }
  public static Offset<SkillInfo> EndSkillInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SkillInfo>(o);
  }
}


static public class SkillInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SkillId*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
