// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum PacketType : byte
{
  NONE = 0,
  C_Test = 1,
  SD_Test = 2,
  D_Test = 3,
  SC_Test = 4,
};



static public class PacketTypeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((PacketType)typeId)
    {
      case PacketType.C_Test:
        result = C_TestVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SD_Test:
        result = SD_TestVerify.Verify(verifier, tablePos);
        break;
      case PacketType.D_Test:
        result = D_TestVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_Test:
        result = SC_TestVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

