// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SD_Test : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_12_23(); }
  public static SD_Test GetRootAsSD_Test(ByteBuffer _bb) { return GetRootAsSD_Test(_bb, new SD_Test()); }
  public static SD_Test GetRootAsSD_Test(ByteBuffer _bb, SD_Test obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SD_Test __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int TestSd { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<SD_Test> CreateSD_Test(FlatBufferBuilder builder,
      int test_sd = 0) {
    builder.StartTable(1);
    SD_Test.AddTestSd(builder, test_sd);
    return SD_Test.EndSD_Test(builder);
  }

  public static void StartSD_Test(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTestSd(FlatBufferBuilder builder, int testSd) { builder.AddInt(0, testSd, 0); }
  public static Offset<SD_Test> EndSD_Test(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SD_Test>(o);
  }
}


static public class SD_TestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*TestSd*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
